export const TEMPLATES = [
  {
    id: 'photoshop',
    name: 'Adobe Photoshop',
    iconSrc: 'icons/photoshop-icon.svg',
    appCategory: 'Design',
    hotkeys: {
      // Tools
      KeyV: { label: 'Move',          description: 'Move tool',                                  category: 'tool',      modifiers: [] },
      KeyL: { label: 'Lasso',         description: 'Lasso tool',                                 category: 'tool',      modifiers: [] },
      KeyW: { label: 'Quick Select',  description: 'Quick selection tool',                       category: 'tool',      modifiers: [] },
      KeyM: { label: 'Marquee',       description: 'Rect / elliptical marquee; Shift+M switches', category: 'tool',     modifiers: [] },
      KeyB: { label: 'Brush',         description: 'Brush tool',                                 category: 'tool',      modifiers: [] },
      KeyE: { label: 'Eraser',        description: 'Eraser tool',                                category: 'tool',      modifiers: [] },
      KeyG: { label: 'Bucket/Grad',   description: 'Paint bucket or gradient; Shift+G switches', category: 'tool',      modifiers: [] },
      KeyJ: { label: 'Spot Heal',     description: 'Spot healing brush',                         category: 'tool',      modifiers: [] },
      KeyS: { label: 'Clone Stamp',   description: 'Clone stamp tool',                           category: 'tool',      modifiers: [] },
      KeyI: { label: 'Eyedropper',    description: 'Sample a color',                             category: 'tool',      modifiers: [] },
      KeyX: { label: 'Swap Colors',   description: 'Switch foreground / background colors',      category: 'tool',      modifiers: [] },
      KeyT: { label: 'Transform',     description: 'Transform tool',                             category: 'tool',      modifiers: ['Ctrl', 'Alt'] },
      // Edit
      KeyZ: { label: 'Undo',          description: '',                                           category: 'edit',      modifiers: ['Ctrl'] },
      // Selection
      KeyA: { label: 'Select All',    description: '',                                           category: 'selection', modifiers: ['Ctrl'] },
      KeyD: { label: 'Deselect',      description: '',                                           category: 'selection', modifiers: ['Ctrl'] },
      // View / Zoom
      Equal:  { label: 'Zoom In',     description: '',                                           category: 'view',      modifiers: ['Ctrl'] },
      Minus:  { label: 'Zoom Out',    description: '',                                           category: 'view',      modifiers: ['Ctrl'] },
      Digit0: { label: 'Fit Screen',  description: 'Zoom to fit',                                category: 'view',      modifiers: ['Ctrl'] },
      Digit1: { label: '100% Zoom',   description: 'Zoom to 100%',                               category: 'view',      modifiers: ['Ctrl'] },
      Digit2: { label: '200% Zoom',   description: 'Zoom to 200%',                               category: 'view',      modifiers: ['Ctrl'] },
      // Layers
      KeyN:         { label: 'New Layer',     description: 'Add new layer',     category: 'edit', modifiers: ['Ctrl', 'Alt', 'Shift'] },
      BracketRight: { label: 'Bring Fwd',     description: 'Bring forward',     category: 'edit', modifiers: ['Ctrl'] },
      BracketLeft:  { label: 'Send Back',     description: 'Send backward',     category: 'edit', modifiers: ['Ctrl'] },
      Comma:        { label: 'Hide Layers',   description: '',                  category: 'edit', modifiers: ['Ctrl'] },
      Slash:        { label: 'Lock Layers',   description: '',                  category: 'edit', modifiers: ['Ctrl'] },
      // Settings
      KeyK: { label: 'Settings',      description: 'Show settings',                              category: 'view',      modifiers: ['Ctrl'] },
    },
  },
  {
    id: 'premiere',
    name: 'Adobe Premiere Pro',
    iconSrc: 'icons/premier-pro-icon.svg',
    appCategory: 'Video',
    hotkeys: {
      // Markers / in-out (bare keys)
      KeyI:      { label: 'Mark In',      description: 'Set in point',                        category: 'selection', modifiers: [] },
      KeyO:      { label: 'Mark Out',     description: 'Set out point',                       category: 'selection', modifiers: [] },
      KeyM:      { label: 'Add Marker',   description: 'Add marker at playhead',              category: 'edit',      modifiers: [] },
      KeyX:      { label: 'Mark Clip',    description: 'Mark in/out to clip edges',           category: 'selection', modifiers: [] },
      Slash:     { label: 'Mark Select',  description: 'Mark selection',                      category: 'selection', modifiers: [] },
      // Sequence editing (bare keys)
      KeyF:      { label: 'Match Frame',  description: 'Match frame to source',               category: 'view',      modifiers: [] },
      KeyE:      { label: 'Extend Edit',  description: 'Extend selected edit to playhead',    category: 'edit',      modifiers: [] },
      Comma:     { label: 'Insert',       description: 'Insert clip at playhead',             category: 'edit',      modifiers: [] },
      Period:    { label: 'Overwrite',    description: 'Overwrite clip at playhead',          category: 'edit',      modifiers: [] },
      Semicolon: { label: 'Lift',         description: 'Lift selection (leaves gap)',         category: 'edit',      modifiers: [] },
      Quote:     { label: 'Extract',      description: 'Extract selection (closes gap)',      category: 'edit',      modifiers: [] },
      Enter:     { label: 'Render',       description: 'Render effects in to out',            category: 'view',      modifiers: [] },
      Equal:     { label: 'Zoom In',      description: 'Zoom into timeline',                  category: 'view',      modifiers: [] },
      Minus:     { label: 'Zoom Out',     description: 'Zoom out of timeline',                category: 'view',      modifiers: [] },
      // Edit menu (Ctrl)
      KeyZ:      { label: 'Undo',         description: '',                                    category: 'edit',      modifiers: ['Ctrl'] },
      KeyA:      { label: 'Select All',   description: '',                                    category: 'selection', modifiers: ['Ctrl'] },
      KeyD:      { label: 'Video Trans',  description: 'Apply default video transition',      category: 'edit',      modifiers: ['Ctrl'] },
      KeyK:      { label: 'Add Edit',     description: 'Cut all tracks at playhead',          category: 'edit',      modifiers: ['Ctrl'] },
      KeyG:      { label: 'Group',        description: 'Group selected clips',                category: 'edit',      modifiers: ['Ctrl'] },
      KeyR:      { label: 'Speed/Dur',    description: 'Speed / Duration dialog',             category: 'edit',      modifiers: ['Ctrl'] },
      KeyL:      { label: 'Link',         description: 'Link / unlink selected clips',        category: 'edit',      modifiers: ['Ctrl'] },
      KeyU:      { label: 'Subclip',      description: 'Make subclip',                       category: 'edit',      modifiers: ['Ctrl'] },
      KeyT:      { label: 'New Text',     description: 'New text layer',                      category: 'edit',      modifiers: ['Ctrl'] },
      // File (Ctrl)
      KeyS:      { label: 'Save',         description: '',                                    category: 'file',      modifiers: ['Ctrl'] },
      KeyN:      { label: 'New Seq',      description: 'New sequence',                        category: 'file',      modifiers: ['Ctrl'] },
      // Window panels (Shift)
      Digit2:    { label: 'Source Mon',   description: 'Focus Source Monitor panel',         category: 'view',      modifiers: ['Shift'] },
      Digit3:    { label: 'Timeline',     description: 'Focus Timeline panel',               category: 'view',      modifiers: ['Shift'] },
      Digit4:    { label: 'Program Mon',  description: 'Focus Program Monitor panel',        category: 'view',      modifiers: ['Shift'] },
    },
  },
  {
    id: 'wow',
    name: 'World of Warcraft',
    iconSrc: 'icons/WoW_icon.svg',
    appCategory: 'Gaming',
    hotkeys: {
      KeyW: { label: 'Move Fwd',      description: 'Move forward',              category: 'movement',  modifiers: [] },
      KeyA: { label: 'Turn Left',     description: 'Turn / strafe left',        category: 'movement',  modifiers: [] },
      KeyS: { label: 'Move Back',     description: 'Move backward',             category: 'movement',  modifiers: [] },
      KeyD: { label: 'Turn Right',    description: 'Turn / strafe right',       category: 'movement',  modifiers: [] },
      KeyQ: { label: 'Strafe L',      description: 'Strafe left',               category: 'movement',  modifiers: [] },
      KeyE: { label: 'Strafe R',      description: 'Strafe right',              category: 'movement',  modifiers: [] },
      Space: { label: 'Jump',         description: '',                           category: 'movement',  modifiers: [] },
      Digit1: { label: 'Ability 1',   category: 'combat',   modifiers: [] },
      Digit2: { label: 'Ability 2',   category: 'combat',   modifiers: [] },
      Digit3: { label: 'Ability 3',   category: 'combat',   modifiers: [] },
      Digit4: { label: 'Ability 4',   category: 'combat',   modifiers: [] },
      Digit5: { label: 'Ability 5',   category: 'combat',   modifiers: [] },
      Digit6: { label: 'Ability 6',   category: 'combat',   modifiers: [] },
      Digit7: { label: 'Ability 7',   category: 'combat',   modifiers: [] },
      Digit8: { label: 'Ability 8',   category: 'combat',   modifiers: [] },
      Digit9: { label: 'Ability 9',   category: 'combat',   modifiers: [] },
      Digit0: { label: 'Ability 10',  category: 'combat',   modifiers: [] },
      Tab: { label: 'Target Enemy',   description: 'Target nearest enemy',      category: 'combat',    modifiers: [] },
      KeyF: { label: 'Interact',      description: 'Interact / target',         category: 'combat',    modifiers: [] },
      KeyB: { label: 'Bags',          description: 'Open all bags',             category: 'tool',      modifiers: [] },
      KeyC: { label: 'Character',     description: 'Character sheet',           category: 'tool',      modifiers: [] },
      KeyI: { label: 'Inventory',     description: 'Open backpack',             category: 'tool',      modifiers: [] },
      KeyM: { label: 'Map',           description: 'Toggle zone map',           category: 'tool',      modifiers: [] },
      KeyN: { label: 'Talents',       description: 'Talent / spec panel',       category: 'tool',      modifiers: [] },
      KeyP: { label: 'Spellbook',     description: 'Open spellbook',            category: 'tool',      modifiers: [] },
      KeyG: { label: 'Guild',         description: 'Open guild roster',         category: 'tool',      modifiers: [] },
      KeyV: { label: 'Nameplates',    description: 'Toggle friendly nameplates',category: 'view',      modifiers: [] },
      ArrowUp:    { label: 'Cam Up',    category: 'view', modifiers: [] },
      ArrowDown:  { label: 'Cam Down',  category: 'view', modifiers: [] },
      ArrowLeft:  { label: 'Cam Left',  category: 'view', modifiers: [] },
      ArrowRight: { label: 'Cam Right', category: 'view', modifiers: [] },
    },
  },
  {
    id: 'cs2',
    name: 'Counter-Strike 2',
    iconSrc: 'icons/cs2-icon.svg',
    iconWide: true,
    appCategory: 'Gaming',
    categories: [
      { id: 'cs2-movement',      name: 'Movement',      color: '#f97316' },
      { id: 'cs2-weapons',       name: 'Weapons',       color: '#ef4444' },
      { id: 'cs2-ui',            name: 'UI',            color: '#3b82f6' },
      { id: 'cs2-communication', name: 'Communication', color: '#22c55e' },
      { id: 'cs2-chat-wheel',    name: 'Chat Wheel',    color: '#a855f7' },
      { id: 'cs2-misc',          name: 'Misc',          color: '#94a3b8' },
    ],
    hotkeys: {
      // Movement
      KeyW:        { label: 'Forward',    description: 'Move forward',                     category: 'cs2-movement',      modifiers: [] },
      KeyS:        { label: 'Back',       description: 'Move backward',                    category: 'cs2-movement',      modifiers: [] },
      KeyA:        { label: 'Strafe L',   description: 'Strafe left',                      category: 'cs2-movement',      modifiers: [] },
      KeyD:        { label: 'Strafe R',   description: 'Strafe right',                     category: 'cs2-movement',      modifiers: [] },
      ShiftLeft:   { label: 'Walk',       description: 'Walk (silent movement)',            category: 'cs2-movement',      modifiers: [] },
      ControlLeft: { label: 'Duck',       description: 'Duck / crouch',                    category: 'cs2-movement',      modifiers: [] },
      Space:       { label: 'Jump',       description: 'Jump',                             category: 'cs2-movement',      modifiers: [] },
      // Weapons
      KeyI:        { label: 'Inventory',  description: 'Toggle inventory display',         category: 'cs2-weapons',       modifiers: [] },
      KeyE:        { label: 'Use',        description: 'Use / interact',                   category: 'cs2-weapons',       modifiers: [] },
      KeyR:        { label: 'Reload',     description: 'Reload weapon',                    category: 'cs2-weapons',       modifiers: [] },
      KeyQ:        { label: 'Last Wpn',   description: 'Switch to last weapon used',       category: 'cs2-weapons',       modifiers: [] },
      KeyG:        { label: 'Drop',       description: 'Drop weapon',                      category: 'cs2-weapons',       modifiers: [] },
      KeyF:        { label: 'Inspect',    description: 'Inspect weapon',                   category: 'cs2-weapons',       modifiers: [] },
      KeyH:        { label: 'Viewmodel',  description: 'Switch viewmodel hand (L/R)',      category: 'cs2-weapons',       modifiers: [] },
      KeyB:        { label: 'Buy Menu',   description: 'Open buy menu',                    category: 'cs2-weapons',       modifiers: [] },
      KeyX:        { label: 'Healthshot', description: 'Use healthshot',                   category: 'cs2-weapons',       modifiers: [] },
      KeyT:        { label: 'Graffiti',   description: 'Open graffiti menu',               category: 'cs2-weapons',       modifiers: [] },
      Digit1:      { label: 'Primary',    description: 'Primary weapon',                   category: 'cs2-weapons',       modifiers: [] },
      Digit2:      { label: 'Secondary',  description: 'Secondary weapon (pistol)',         category: 'cs2-weapons',       modifiers: [] },
      Digit3:      { label: 'Melee',      description: 'Melee weapon (knife)',              category: 'cs2-weapons',       modifiers: [] },
      Digit4:      { label: 'Grenades',   description: 'Cycle grenades',                   category: 'cs2-weapons',       modifiers: [] },
      Digit5:      { label: 'Explosive',  description: 'Explosives & traps (C4)',          category: 'cs2-weapons',       modifiers: [] },
      Digit6:      { label: 'HE Nade',    description: 'HE grenade',                       category: 'cs2-weapons',       modifiers: [] },
      Digit7:      { label: 'Flash',      description: 'Flashbang',                        category: 'cs2-weapons',       modifiers: [] },
      Digit8:      { label: 'Smoke',      description: 'Smoke grenade',                    category: 'cs2-weapons',       modifiers: [] },
      Digit9:      { label: 'Decoy',      description: 'Decoy grenade',                    category: 'cs2-weapons',       modifiers: [] },
      Digit0:      { label: 'Molotov',    description: 'Molotov / incendiary grenade',     category: 'cs2-weapons',       modifiers: [] },
      F3:          { label: 'Autobuy',    description: 'Auto-buy best available equipment', category: 'cs2-weapons',      modifiers: [] },
      F4:          { label: 'Rebuy',      description: 'Rebuy previous loadout',            category: 'cs2-weapons',      modifiers: [] },
      // UI
      Tab:         { label: 'Scoreboard', description: 'Show scoreboard',                  category: 'cs2-ui',            modifiers: [] },
      KeyM:        { label: 'Team',       description: 'Open team selection',              category: 'cs2-ui',            modifiers: [] },
      Backquote:   { label: 'Console',    description: 'Toggle developer console',         category: 'cs2-ui',            modifiers: [] },
      // Communication
      KeyZ:        { label: 'Radio',      description: 'Radio message menu',               category: 'cs2-communication', modifiers: [] },
      KeyU:        { label: 'Team Chat',  description: 'Send team message',                category: 'cs2-communication', modifiers: [] },
      KeyY:        { label: 'Chat',       description: 'Send all-chat message',            category: 'cs2-communication', modifiers: [] },
      // Chat Wheel
      KeyC:        { label: 'Wheel 1',    description: 'Chat wheel 1',                     category: 'cs2-chat-wheel',    modifiers: [] },
      KeyV:        { label: 'Wheel 2',    description: 'Chat wheel 2',                     category: 'cs2-chat-wheel',    modifiers: [] },
      // Misc
      F1:          { label: 'Auto Buy',   description: 'Automatically buy equipment',      category: 'cs2-misc',          modifiers: [] },
      F2:          { label: 'Rebuy Prev', description: 'Rebuy previous equipment',         category: 'cs2-misc',          modifiers: [] },
      F12:         { label: 'Screenshot', description: 'Take screenshot',                  category: 'cs2-misc',          modifiers: [] },
    },
  },
  {
    id: 'vscode',
    name: 'VS Code',
    iconSrc: 'icons/vscode_icon.svg',
    appCategory: 'Development',
    hotkeys: {
      KeyS: { label: 'Save',          description: 'Save file',                 category: 'file',      modifiers: ['Ctrl'] },
      KeyW: { label: 'Close Tab',     description: 'Close editor tab',          category: 'file',      modifiers: ['Ctrl'] },
      KeyN: { label: 'New File',      description: 'New untitled file',         category: 'file',      modifiers: ['Ctrl'] },
      KeyP: { label: 'Quick Open',    description: 'Open file by name',         category: 'file',      modifiers: ['Ctrl'] },
      KeyZ: { label: 'Undo',          description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
      KeyY: { label: 'Redo',          description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
      KeyX: { label: 'Cut',           description: 'Cut line or selection',     category: 'edit',      modifiers: ['Ctrl'] },
      KeyC: { label: 'Copy',          description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
      KeyV: { label: 'Paste',         description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
      KeyD: { label: 'Select Next',   description: 'Select next occurrence',    category: 'selection', modifiers: ['Ctrl'] },
      Slash: { label: 'Comment',      description: 'Toggle line comment',       category: 'edit',      modifiers: ['Ctrl'] },
      KeyF: { label: 'Find',          description: 'Find in file',              category: 'edit',      modifiers: ['Ctrl'] },
      KeyH: { label: 'Replace',       description: 'Find and replace',          category: 'edit',      modifiers: ['Ctrl'] },
      KeyG: { label: 'Go to Line',    description: 'Jump to line number',       category: 'movement',  modifiers: ['Ctrl'] },
      KeyB: { label: 'Sidebar',       description: 'Toggle activity bar',       category: 'view',      modifiers: ['Ctrl'] },
      Backquote: { label: 'Terminal', description: 'Toggle integrated terminal',category: 'view',      modifiers: ['Ctrl'] },
      F2:  { label: 'Rename',         description: 'Rename symbol',             category: 'edit',      modifiers: [] },
      F12: { label: 'Go to Def',      description: 'Go to definition',          category: 'movement',  modifiers: [] },
      F5:  { label: 'Debug',          description: 'Start / continue debug',    category: 'tool',      modifiers: [] },
      Home: { label: 'Line Start',    description: 'Go to line beginning',      category: 'movement',  modifiers: [] },
      End:  { label: 'Line End',      description: 'Go to line end',            category: 'movement',  modifiers: [] },
    },
  },
  {
    id: 'bf6',
    name: 'Battlefield 6',
    iconSrc: 'icons/bf6-icon.svg',
    iconClass: 'template-logo template-logo--wide-xl',
    appCategory: 'Gaming',
    categories: [
      { id: 'bf6-general',  name: 'General',            color: '#6366f1' },
      { id: 'bf6-movement', name: 'Movement',            color: '#f97316' },
      { id: 'bf6-weapons',  name: 'Weapons',             color: '#ef4444' },
      { id: 'bf6-ui',       name: 'UI',                  color: '#3b82f6' },
    ],
    tabs: [
      {
        name: 'Infantry',
        hotkeys: {
          // Movement
          KeyW:        { label: 'Forward',     description: 'Walk forward',                                   category: 'bf6-movement', modifiers: [] },
          KeyS:        { label: 'Backward',    description: 'Walk backward',                                  category: 'bf6-movement', modifiers: [] },
          KeyD:        { label: 'Strafe R',    description: 'Strafe right',                                   category: 'bf6-movement', modifiers: [] },
          KeyA:        { label: 'Strafe L',    description: 'Strafe left',                                    category: 'bf6-movement', modifiers: [] },
          Space:       { label: 'Jump/Vault',  description: 'Jump, vault, parachute deploy',                  category: 'bf6-movement', modifiers: [] },
          ShiftLeft:   { label: 'Sprint',      description: 'Sprint',                                         category: 'bf6-movement', modifiers: [] },
          ControlLeft: { label: 'Crouch',      description: 'Crouch (hold)',                                  category: 'bf6-movement', modifiers: [] },
          KeyC:        { label: 'Crouch Tog',  description: 'Crouch (toggle)',                                category: 'bf6-movement', modifiers: [] },
          KeyZ:        { label: 'Prone',       description: 'Prone',                                          category: 'bf6-movement', modifiers: [] },
          // General
          KeyE:        { label: 'Interact',    description: 'Interact / Quick Upgrade (hold) / Enter vehicle', category: 'bf6-general',  modifiers: [] },
          KeyM:        { label: 'Big Map',     description: 'Open big map',                                   category: 'bf6-general',  modifiers: [] },
          KeyY:        { label: 'Loadout',     description: 'Quick Loadout Customization',                    category: 'bf6-general',  modifiers: [] },
          Tab:         { label: 'Inventory',   description: 'Toggle Inventory / Scoreboard (hold)',           category: 'bf6-general',  modifiers: [] },
          KeyQ:        { label: 'Ping/Commo',  description: 'Ping / CommoRose (hold) / Call-in gadget',      category: 'bf6-general',  modifiers: [] },
          // Weapons & Equipment
          KeyR:        { label: 'Reload',      description: 'Reload (tap) / Interact (hold)',                 category: 'bf6-weapons',  modifiers: [] },
          KeyF:        { label: 'Melee',       description: 'Melee / melee takedown',                         category: 'bf6-weapons',  modifiers: [] },
          Digit1:      { label: 'Primary',     description: 'Primary weapon',                                 category: 'bf6-weapons',  modifiers: [] },
          Digit2:      { label: 'Secondary',   description: 'Secondary weapon',                               category: 'bf6-weapons',  modifiers: [] },
          KeyI:        { label: 'Inspect',     description: 'Weapon inspect',                                 category: 'bf6-weapons',  modifiers: [] },
          Digit3:      { label: 'Gadget 1',    description: 'Gadget one',                                     category: 'bf6-weapons',  modifiers: [] },
          Digit4:      { label: 'Gadget 2',    description: 'Gadget two',                                     category: 'bf6-weapons',  modifiers: [] },
          KeyX:        { label: 'Class Gadget',description: 'Squad progression / class gadget',               category: 'bf6-weapons',  modifiers: [] },
          Digit7:      { label: 'Night Vision',description: 'Night Vision Goggles',                           category: 'bf6-weapons',  modifiers: [] },
          KeyG:        { label: 'Grenade',     description: 'Grenade',                                        category: 'bf6-weapons',  modifiers: [] },
          Digit6:      { label: 'Class Abil',  description: 'Class Ability and Call-In Gadget',               category: 'bf6-weapons',  modifiers: [] },
          KeyT:        { label: 'Laser/Light', description: 'Toggle laser and/or flashlight',                 category: 'bf6-weapons',  modifiers: [] },
          KeyV:        { label: 'Toggl Scope', description: 'Toggle scope',                                   category: 'bf6-weapons',  modifiers: [] },
        },
      },
      {
        name: 'Ground Vehicle',
        hotkeys: {
          // Movement
          KeyW:        { label: 'Accelerate',  description: 'Accelerate',                                     category: 'bf6-movement', modifiers: [] },
          KeyS:        { label: 'Brake/Rev',   description: 'Brake / reverse',                                category: 'bf6-movement', modifiers: [] },
          KeyD:        { label: 'Turn Right',  description: 'Turn right',                                     category: 'bf6-movement', modifiers: [] },
          KeyA:        { label: 'Turn Left',   description: 'Turn left',                                      category: 'bf6-movement', modifiers: [] },
          ShiftLeft:   { label: 'Boost',       description: 'Boost',                                          category: 'bf6-movement', modifiers: [] },
          KeyZ:        { label: 'Handbrake',   description: 'Handbrake',                                      category: 'bf6-movement', modifiers: [] },
          KeyV:        { label: 'Lock Turret', description: 'Lock turret',                                    category: 'bf6-movement', modifiers: [] },
          // General
          KeyE:        { label: 'Exit',        description: 'Exit vehicle',                                   category: 'bf6-general',  modifiers: [] },
          KeyM:        { label: 'Big Map',     description: 'Open big map',                                   category: 'bf6-general',  modifiers: [] },
          KeyY:        { label: 'Loadout',     description: 'Quick loadout customization',                    category: 'bf6-general',  modifiers: [] },
          Tab:         { label: 'Inventory',   description: 'Toggle inventory / scoreboard (hold)',           category: 'bf6-general',  modifiers: [] },
          KeyC:        { label: 'Chase Cam',   description: 'Chase camera',                                   category: 'bf6-general',  modifiers: [] },
          KeyQ:        { label: 'Ping/Commo',  description: 'Ping / CommoRose / Call-in gadget',              category: 'bf6-general',  modifiers: [] },
          // Weapons & Equipment
          Space:       { label: 'Fire',        description: 'Fire weapon',                                    category: 'bf6-weapons',  modifiers: [] },
          Digit1:      { label: 'Primary',     description: 'Primary weapon',                                 category: 'bf6-weapons',  modifiers: [] },
          Digit2:      { label: 'Secondary',   description: 'Secondary weapon',                               category: 'bf6-weapons',  modifiers: [] },
          Digit3:      { label: 'Equipment 1', description: 'Activate equipment slot 1',                      category: 'bf6-weapons',  modifiers: [] },
          Digit4:      { label: 'Equipment 2', description: 'Activate equipment slot 2',                      category: 'bf6-weapons',  modifiers: [] },
          KeyF:        { label: 'Switch Wpn',  description: 'Switch weapon',                                  category: 'bf6-weapons',  modifiers: [] },
        },
      },
      {
        name: 'Transport Vehicle',
        hotkeys: {
          // Movement
          KeyW:        { label: 'Accelerate',  description: 'Accelerate',                                     category: 'bf6-movement', modifiers: [] },
          KeyS:        { label: 'Brake/Rev',   description: 'Brake / reverse',                                category: 'bf6-movement', modifiers: [] },
          KeyD:        { label: 'Turn Right',  description: 'Turn right',                                     category: 'bf6-movement', modifiers: [] },
          KeyA:        { label: 'Turn Left',   description: 'Turn left',                                      category: 'bf6-movement', modifiers: [] },
          ControlLeft: { label: 'Boost',       description: 'Boost',                                          category: 'bf6-movement', modifiers: [] },
          ArrowUp:     { label: 'Look Up',     description: 'Freelook up',                                    category: 'bf6-movement', modifiers: [] },
          ArrowDown:   { label: 'Look Down',   description: 'Freelook down',                                  category: 'bf6-movement', modifiers: [] },
          ArrowRight:  { label: 'Look Right',  description: 'Freelook right',                                 category: 'bf6-movement', modifiers: [] },
          ArrowLeft:   { label: 'Look Left',   description: 'Freelook left',                                  category: 'bf6-movement', modifiers: [] },
          // General
          KeyE:        { label: 'Exit',        description: 'Exit vehicle',                                   category: 'bf6-general',  modifiers: [] },
          KeyM:        { label: 'Big Map',     description: 'Open big map',                                   category: 'bf6-general',  modifiers: [] },
          Tab:         { label: 'Inventory',   description: 'Toggle inventory / scoreboard',                  category: 'bf6-general',  modifiers: [] },
          KeyC:        { label: 'Chase Cam',   description: 'Chase camera',                                   category: 'bf6-general',  modifiers: [] },
          KeyZ:        { label: 'Handbrake',   description: 'Handbrake',                                      category: 'bf6-general',  modifiers: [] },
          KeyQ:        { label: 'Ping/Commo',  description: 'Ping / CommoRose / Call-in gadget',              category: 'bf6-general',  modifiers: [] },
          KeyV:        { label: 'Freelook',    description: 'Freelook',                                       category: 'bf6-general',  modifiers: [] },
        },
      },
      {
        name: 'Aircraft',
        hotkeys: {
          // Movement
          KeyW:        { label: 'Throttle Up', description: 'Throttle up',                                    category: 'bf6-movement', modifiers: [] },
          KeyS:        { label: 'Throttle Dn', description: 'Throttle down',                                  category: 'bf6-movement', modifiers: [] },
          KeyD:        { label: 'Yaw Right',   description: 'Yaw right',                                      category: 'bf6-movement', modifiers: [] },
          KeyA:        { label: 'Yaw Left',    description: 'Yaw left',                                       category: 'bf6-movement', modifiers: [] },
          ArrowDown:   { label: 'Pitch Down',  description: 'Pitch down',                                     category: 'bf6-movement', modifiers: [] },
          ArrowUp:     { label: 'Pitch Up',    description: 'Pitch up',                                       category: 'bf6-movement', modifiers: [] },
          ArrowRight:  { label: 'Roll Right',  description: 'Roll right',                                     category: 'bf6-movement', modifiers: [] },
          ArrowLeft:   { label: 'Roll Left',   description: 'Roll left',                                      category: 'bf6-movement', modifiers: [] },
          ShiftLeft:   { label: 'Afterburner', description: 'Afterburner',                                    category: 'bf6-movement', modifiers: [] },
          KeyV:        { label: 'Freelook',    description: 'Freelook',                                       category: 'bf6-movement', modifiers: [] },
          // General
          KeyE:        { label: 'Exit',        description: 'Exit vehicle',                                   category: 'bf6-general',  modifiers: [] },
          KeyM:        { label: 'Big Map',     description: 'Open big map',                                   category: 'bf6-general',  modifiers: [] },
          Tab:         { label: 'Inventory',   description: 'Toggle inventory / scoreboard',                  category: 'bf6-general',  modifiers: [] },
          KeyY:        { label: 'Loadout',     description: 'Quick loadout customization',                    category: 'bf6-general',  modifiers: [] },
          KeyC:        { label: 'Chase Cam',   description: 'Chase camera',                                   category: 'bf6-general',  modifiers: [] },
          KeyQ:        { label: 'Ping/Commo',  description: 'Ping / CommoRose / Call-in gadget',              category: 'bf6-general',  modifiers: [] },
          // Weapons & Equipment
          Digit1:      { label: 'Primary',     description: 'Primary weapon',                                 category: 'bf6-weapons',  modifiers: [] },
          Digit2:      { label: 'Secondary',   description: 'Secondary weapon',                               category: 'bf6-weapons',  modifiers: [] },
          Digit3:      { label: 'Equipment 1', description: 'Activate equipment slot 1',                      category: 'bf6-weapons',  modifiers: [] },
          Digit4:      { label: 'Equipment 2', description: 'Activate equipment slot 2',                      category: 'bf6-weapons',  modifiers: [] },
          KeyF:        { label: 'Switch Wpn',  description: 'Switch weapon',                                  category: 'bf6-weapons',  modifiers: [] },
        },
      },
      {
        name: 'Helicopter',
        hotkeys: {
          // Movement
          KeyW:        { label: 'Throttle Up', description: 'Throttle up',                                    category: 'bf6-movement', modifiers: [] },
          KeyS:        { label: 'Throttle Dn', description: 'Throttle down',                                  category: 'bf6-movement', modifiers: [] },
          KeyD:        { label: 'Yaw Right',   description: 'Yaw right',                                      category: 'bf6-movement', modifiers: [] },
          KeyA:        { label: 'Yaw Left',    description: 'Yaw left',                                       category: 'bf6-movement', modifiers: [] },
          ArrowDown:   { label: 'Pitch Down',  description: 'Pitch down',                                     category: 'bf6-movement', modifiers: [] },
          ArrowUp:     { label: 'Pitch Up',    description: 'Pitch up',                                       category: 'bf6-movement', modifiers: [] },
          ArrowRight:  { label: 'Roll Right',  description: 'Roll right',                                     category: 'bf6-movement', modifiers: [] },
          ArrowLeft:   { label: 'Roll Left',   description: 'Roll left',                                      category: 'bf6-movement', modifiers: [] },
          Space:       { label: 'Ascend',      description: 'Heli assist ascend',                             category: 'bf6-movement', modifiers: [] },
          ControlLeft: { label: 'Descend',     description: 'Heli assist descend',                            category: 'bf6-movement', modifiers: [] },
          KeyV:        { label: 'Freelook',    description: 'Freelook',                                       category: 'bf6-movement', modifiers: [] },
          // General
          KeyE:        { label: 'Exit',        description: 'Exit vehicle',                                   category: 'bf6-general',  modifiers: [] },
          KeyM:        { label: 'Big Map',     description: 'Open big map',                                   category: 'bf6-general',  modifiers: [] },
          KeyY:        { label: 'Loadout',     description: 'Quick loadout customization',                    category: 'bf6-general',  modifiers: [] },
          Tab:         { label: 'Inventory',   description: 'Toggle inventory / scoreboard',                  category: 'bf6-general',  modifiers: [] },
          KeyC:        { label: 'Chase Cam',   description: 'Chase camera',                                   category: 'bf6-general',  modifiers: [] },
          KeyQ:        { label: 'Ping/Commo',  description: 'Ping / CommoRose / Call-in gadget',              category: 'bf6-general',  modifiers: [] },
          // Weapons & Equipment
          Digit1:      { label: 'Primary',     description: 'Primary weapon',                                 category: 'bf6-weapons',  modifiers: [] },
          Digit2:      { label: 'Secondary',   description: 'Secondary weapon',                               category: 'bf6-weapons',  modifiers: [] },
          Digit3:      { label: 'Equipment 1', description: 'Activate equipment slot 1',                      category: 'bf6-weapons',  modifiers: [] },
          Digit4:      { label: 'Equipment 2', description: 'Activate equipment slot 2',                      category: 'bf6-weapons',  modifiers: [] },
          KeyF:        { label: 'Switch Wpn',  description: 'Switch weapon',                                  category: 'bf6-weapons',  modifiers: [] },
        },
      },
      {
        name: 'Gunner',
        hotkeys: {
          // Movement
          ArrowUp:     { label: 'Aim Up',      description: 'Aim up',                                         category: 'bf6-movement', modifiers: [] },
          ArrowDown:   { label: 'Aim Down',    description: 'Aim down',                                       category: 'bf6-movement', modifiers: [] },
          ArrowRight:  { label: 'Aim Right',   description: 'Aim right',                                      category: 'bf6-movement', modifiers: [] },
          ArrowLeft:   { label: 'Aim Left',    description: 'Aim left',                                       category: 'bf6-movement', modifiers: [] },
          // General
          KeyR:        { label: 'Reload',      description: 'Reload',                                         category: 'bf6-general',  modifiers: [] },
          KeyE:        { label: 'Exit',        description: 'Exit vehicle',                                   category: 'bf6-general',  modifiers: [] },
          KeyM:        { label: 'Big Map',     description: 'Open big map',                                   category: 'bf6-general',  modifiers: [] },
          KeyY:        { label: 'Loadout',     description: 'Quick loadout customization',                    category: 'bf6-general',  modifiers: [] },
          Tab:         { label: 'Inventory',   description: 'Toggle inventory / scoreboard (hold)',           category: 'bf6-general',  modifiers: [] },
          KeyQ:        { label: 'Ping/Commo',  description: 'Ping / CommoRose / Call-in gadget',              category: 'bf6-general',  modifiers: [] },
          // Weapons & Equipment
          Space:       { label: 'Fire',        description: 'Fire weapon',                                    category: 'bf6-weapons',  modifiers: [] },
          Digit1:      { label: 'Primary',     description: 'Primary weapon',                                 category: 'bf6-weapons',  modifiers: [] },
          Digit2:      { label: 'Secondary',   description: 'Secondary weapon',                               category: 'bf6-weapons',  modifiers: [] },
          Digit3:      { label: 'Equipment',   description: 'Activate equipment slot',                        category: 'bf6-weapons',  modifiers: [] },
          KeyF:        { label: 'Switch Wpn',  description: 'Switch weapon',                                  category: 'bf6-weapons',  modifiers: [] },
        },
      },
      {
        name: 'UI',
        hotkeys: {
          Tab:      { label: 'Scoreboard',  description: 'Show scoreboard',                          category: 'bf6-ui', modifiers: [] },
          KeyM:     { label: 'Big Map',     description: 'Open big map',                             category: 'bf6-ui', modifiers: [] },
          Enter:    { label: 'Chat',        description: 'Open chat',                                category: 'bf6-ui', modifiers: [] },
          KeyK:     { label: 'Team Chat',   description: 'Team chat channel',                        category: 'bf6-ui', modifiers: [] },
          CapsLock: { label: 'Push Talk',   description: 'Push to talk',                             category: 'bf6-ui', modifiers: [] },
          KeyL:     { label: 'Squad Chat',  description: 'Squad chat channel',                       category: 'bf6-ui', modifiers: [] },
          KeyP:     { label: 'Party Chat',  description: 'Party chat channel',                       category: 'bf6-ui', modifiers: [] },
          KeyJ:     { label: 'Chat All',    description: 'Send message to all',                      category: 'bf6-ui', modifiers: [] },
          KeyH:     { label: 'Toggle Chat', description: 'Toggle chat visibility',                   category: 'bf6-ui', modifiers: [] },
          KeyQ:     { label: 'Ping/Commo',  description: 'Ping / CommoRose (hold)',                  category: 'bf6-ui', modifiers: [] },
          KeyT:     { label: 'Clear Ping',  description: 'Clear ping',                               category: 'bf6-ui', modifiers: [] },
          KeyE:     { label: 'Inspect Wpn', description: 'Inspect weapon in CommoRose',              category: 'bf6-ui', modifiers: [] },
          KeyG:     { label: 'Inv Request', description: 'Inventory request',                        category: 'bf6-ui', modifiers: [] },
        },
      },
    ],
  },
];
