const TEMPLATES = [
  {
    id: 'photoshop',
    name: 'Adobe Photoshop',
    icon: '🎨',
    appCategory: 'Design',
    hotkeys: {
      KeyV: { label: 'Move',          description: 'Move tool',                category: 'tool',      modifiers: [] },
      KeyM: { label: 'Marquee',       description: 'Rectangular / elliptical', category: 'selection', modifiers: [] },
      KeyL: { label: 'Lasso',         description: 'Lasso selection',          category: 'selection', modifiers: [] },
      KeyW: { label: 'Quick Select',  description: 'Quick selection / wand',   category: 'selection', modifiers: [] },
      KeyC: { label: 'Crop',          description: 'Crop tool',                category: 'tool',      modifiers: [] },
      KeyI: { label: 'Eyedropper',    description: 'Sample color',             category: 'tool',      modifiers: [] },
      KeyJ: { label: 'Spot Heal',     description: 'Spot healing brush',       category: 'tool',      modifiers: [] },
      KeyB: { label: 'Brush',         description: 'Brush / pencil',           category: 'tool',      modifiers: [] },
      KeyS: { label: 'Clone Stamp',   description: 'Clone / pattern stamp',    category: 'tool',      modifiers: [] },
      KeyE: { label: 'Eraser',        description: 'Eraser tool',              category: 'tool',      modifiers: [] },
      KeyG: { label: 'Gradient',      description: 'Gradient / paint bucket',  category: 'tool',      modifiers: [] },
      KeyO: { label: 'Dodge/Burn',    description: 'Dodge, burn, or sponge',   category: 'tool',      modifiers: [] },
      KeyP: { label: 'Pen',           description: 'Pen path tool',            category: 'tool',      modifiers: [] },
      KeyT: { label: 'Type',          description: 'Horizontal type tool',     category: 'tool',      modifiers: [] },
      KeyA: { label: 'Path Select',   description: 'Direct / path selection',  category: 'tool',      modifiers: [] },
      KeyH: { label: 'Hand',          description: 'Pan the canvas',           category: 'view',      modifiers: [] },
      KeyZ: { label: 'Zoom',          description: 'Zoom tool',                category: 'view',      modifiers: [] },
      KeyX: { label: 'Swap Colors',   description: 'Swap foreground / bg',     category: 'tool',      modifiers: [] },
      KeyD: { label: 'Reset Colors',  description: 'Reset to black & white',   category: 'tool',      modifiers: [] },
      Space: { label: 'Pan',          description: 'Hold to pan with hand',    category: 'view',      modifiers: [] },
      BracketLeft:  { label: 'Brush −', description: 'Decrease brush size',    category: 'tool',      modifiers: [] },
      BracketRight: { label: 'Brush +', description: 'Increase brush size',    category: 'tool',      modifiers: [] },
      F5: { label: 'Brushes',         description: 'Open Brushes panel',       category: 'view',      modifiers: [] },
      F7: { label: 'Layers',          description: 'Open Layers panel',        category: 'view',      modifiers: [] },
    },
  },
  {
    id: 'premiere',
    name: 'Adobe Premiere Pro',
    icon: '🎬',
    appCategory: 'Video',
    hotkeys: {
      Space: { label: 'Play/Pause',   description: 'Toggle playback',            category: 'tool',      modifiers: [] },
      KeyJ: { label: 'Rewind',        description: 'Play backwards',             category: 'movement',  modifiers: [] },
      KeyK: { label: 'Stop',          description: 'Stop playback',              category: 'movement',  modifiers: [] },
      KeyL: { label: 'Fast Fwd',      description: 'Play forward (press again to speed up)', category: 'movement', modifiers: [] },
      KeyI: { label: 'In Point',      description: 'Set clip in point',          category: 'edit',      modifiers: [] },
      KeyO: { label: 'Out Point',     description: 'Set clip out point',         category: 'edit',      modifiers: [] },
      KeyV: { label: 'Select',        description: 'Selection tool',             category: 'tool',      modifiers: [] },
      KeyC: { label: 'Razor',         description: 'Razor / cut tool',           category: 'tool',      modifiers: [] },
      KeyB: { label: 'Ripple Edit',   description: 'Ripple edit tool',           category: 'tool',      modifiers: [] },
      KeyN: { label: 'Rate Stretch',  description: 'Rate stretch tool',          category: 'tool',      modifiers: [] },
      KeyR: { label: 'Roll Edit',     description: 'Rolling edit tool',          category: 'tool',      modifiers: [] },
      KeyY: { label: 'Slip',          description: 'Slip tool',                  category: 'tool',      modifiers: [] },
      KeyU: { label: 'Slide',         description: 'Slide tool',                 category: 'tool',      modifiers: [] },
      KeyQ: { label: 'Trim Prev',     description: 'Ripple trim previous edit',  category: 'edit',      modifiers: [] },
      KeyW: { label: 'Trim Next',     description: 'Ripple trim next edit',      category: 'edit',      modifiers: [] },
      KeyD: { label: 'Select Clip',   description: 'Select clip at playhead',    category: 'selection', modifiers: [] },
      KeyM: { label: 'Marker',        description: 'Add timeline marker',        category: 'edit',      modifiers: [] },
      ArrowLeft:  { label: 'Prev Frame', description: 'Step one frame back',     category: 'movement',  modifiers: [] },
      ArrowRight: { label: 'Next Frame', description: 'Step one frame forward',  category: 'movement',  modifiers: [] },
      Home: { label: 'Go to Start',   description: 'Jump to sequence start',     category: 'movement',  modifiers: [] },
      End:  { label: 'Go to End',     description: 'Jump to sequence end',       category: 'movement',  modifiers: [] },
      KeyS: { label: 'Save',          description: '',                           category: 'file',      modifiers: ['Ctrl'] },
      KeyZ: { label: 'Undo',          description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
    },
  },
  {
    id: 'wow',
    name: 'World of Warcraft',
    icon: '⚔️',
    appCategory: 'Gaming',
    hotkeys: {
      KeyW: { label: 'Move Fwd',      description: 'Move forward',              category: 'movement',  modifiers: [] },
      KeyA: { label: 'Turn Left',     description: 'Turn / strafe left',        category: 'movement',  modifiers: [] },
      KeyS: { label: 'Move Back',     description: 'Move backward',             category: 'movement',  modifiers: [] },
      KeyD: { label: 'Turn Right',    description: 'Turn / strafe right',       category: 'movement',  modifiers: [] },
      KeyQ: { label: 'Strafe L',      description: 'Strafe left',               category: 'movement',  modifiers: [] },
      KeyE: { label: 'Strafe R',      description: 'Strafe right',              category: 'movement',  modifiers: [] },
      Space: { label: 'Jump',         description: '',                           category: 'movement',  modifiers: [] },
      Digit1: { label: 'Ability 1',   category: 'combat',   modifiers: [] },
      Digit2: { label: 'Ability 2',   category: 'combat',   modifiers: [] },
      Digit3: { label: 'Ability 3',   category: 'combat',   modifiers: [] },
      Digit4: { label: 'Ability 4',   category: 'combat',   modifiers: [] },
      Digit5: { label: 'Ability 5',   category: 'combat',   modifiers: [] },
      Digit6: { label: 'Ability 6',   category: 'combat',   modifiers: [] },
      Digit7: { label: 'Ability 7',   category: 'combat',   modifiers: [] },
      Digit8: { label: 'Ability 8',   category: 'combat',   modifiers: [] },
      Digit9: { label: 'Ability 9',   category: 'combat',   modifiers: [] },
      Digit0: { label: 'Ability 10',  category: 'combat',   modifiers: [] },
      Tab: { label: 'Target Enemy',   description: 'Target nearest enemy',      category: 'combat',    modifiers: [] },
      KeyF: { label: 'Interact',      description: 'Interact / target',         category: 'combat',    modifiers: [] },
      KeyB: { label: 'Bags',          description: 'Open all bags',             category: 'tool',      modifiers: [] },
      KeyC: { label: 'Character',     description: 'Character sheet',           category: 'tool',      modifiers: [] },
      KeyI: { label: 'Inventory',     description: 'Open backpack',             category: 'tool',      modifiers: [] },
      KeyM: { label: 'Map',           description: 'Toggle zone map',           category: 'tool',      modifiers: [] },
      KeyN: { label: 'Talents',       description: 'Talent / spec panel',       category: 'tool',      modifiers: [] },
      KeyP: { label: 'Spellbook',     description: 'Open spellbook',            category: 'tool',      modifiers: [] },
      KeyG: { label: 'Guild',         description: 'Open guild roster',         category: 'tool',      modifiers: [] },
      KeyV: { label: 'Nameplates',    description: 'Toggle friendly nameplates',category: 'view',      modifiers: [] },
      ArrowUp:    { label: 'Cam Up',    category: 'view', modifiers: [] },
      ArrowDown:  { label: 'Cam Down',  category: 'view', modifiers: [] },
      ArrowLeft:  { label: 'Cam Left',  category: 'view', modifiers: [] },
      ArrowRight: { label: 'Cam Right', category: 'view', modifiers: [] },
    },
  },
  {
    id: 'vscode',
    name: 'VS Code',
    icon: '💻',
    appCategory: 'Development',
    hotkeys: {
      KeyS: { label: 'Save',          description: 'Save file',                 category: 'file',      modifiers: ['Ctrl'] },
      KeyW: { label: 'Close Tab',     description: 'Close editor tab',          category: 'file',      modifiers: ['Ctrl'] },
      KeyN: { label: 'New File',      description: 'New untitled file',         category: 'file',      modifiers: ['Ctrl'] },
      KeyP: { label: 'Quick Open',    description: 'Open file by name',         category: 'file',      modifiers: ['Ctrl'] },
      KeyZ: { label: 'Undo',          description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
      KeyY: { label: 'Redo',          description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
      KeyX: { label: 'Cut',           description: 'Cut line or selection',     category: 'edit',      modifiers: ['Ctrl'] },
      KeyC: { label: 'Copy',          description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
      KeyV: { label: 'Paste',         description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
      KeyD: { label: 'Select Next',   description: 'Select next occurrence',    category: 'selection', modifiers: ['Ctrl'] },
      Slash: { label: 'Comment',      description: 'Toggle line comment',       category: 'edit',      modifiers: ['Ctrl'] },
      KeyF: { label: 'Find',          description: 'Find in file',              category: 'edit',      modifiers: ['Ctrl'] },
      KeyH: { label: 'Replace',       description: 'Find and replace',          category: 'edit',      modifiers: ['Ctrl'] },
      KeyG: { label: 'Go to Line',    description: 'Jump to line number',       category: 'movement',  modifiers: ['Ctrl'] },
      KeyB: { label: 'Sidebar',       description: 'Toggle activity bar',       category: 'view',      modifiers: ['Ctrl'] },
      Backquote: { label: 'Terminal', description: 'Toggle integrated terminal',category: 'view',      modifiers: ['Ctrl'] },
      F2:  { label: 'Rename',         description: 'Rename symbol',             category: 'edit',      modifiers: [] },
      F12: { label: 'Go to Def',      description: 'Go to definition',          category: 'movement',  modifiers: [] },
      F5:  { label: 'Debug',          description: 'Start / continue debug',    category: 'tool',      modifiers: [] },
      Home: { label: 'Line Start',    description: 'Go to line beginning',      category: 'movement',  modifiers: [] },
      End:  { label: 'Line End',      description: 'Go to line end',            category: 'movement',  modifiers: [] },
    },
  },
];
