const TEMPLATES = [
  {
    id: 'photoshop',
    name: 'Adobe Photoshop',
    icon: '<img src="icons/photoshop-icon.svg" alt="Adobe Photoshop" class="template-logo">',
    appCategory: 'Design',
    hotkeys: {
      // Tools
      KeyV: { label: 'Move',          description: 'Move tool',                                  category: 'tool',      modifiers: [] },
      KeyL: { label: 'Lasso',         description: 'Lasso tool',                                 category: 'tool',      modifiers: [] },
      KeyW: { label: 'Quick Select',  description: 'Quick selection tool',                       category: 'tool',      modifiers: [] },
      KeyM: { label: 'Marquee',       description: 'Rect / elliptical marquee; Shift+M switches', category: 'tool',     modifiers: [] },
      KeyB: { label: 'Brush',         description: 'Brush tool',                                 category: 'tool',      modifiers: [] },
      KeyE: { label: 'Eraser',        description: 'Eraser tool',                                category: 'tool',      modifiers: [] },
      KeyG: { label: 'Bucket/Grad',   description: 'Paint bucket or gradient; Shift+G switches', category: 'tool',      modifiers: [] },
      KeyJ: { label: 'Spot Heal',     description: 'Spot healing brush',                         category: 'tool',      modifiers: [] },
      KeyS: { label: 'Clone Stamp',   description: 'Clone stamp tool',                           category: 'tool',      modifiers: [] },
      KeyI: { label: 'Eyedropper',    description: 'Sample a color',                             category: 'tool',      modifiers: [] },
      KeyX: { label: 'Swap Colors',   description: 'Switch foreground / background colors',      category: 'tool',      modifiers: [] },
      KeyT: { label: 'Transform',     description: 'Transform tool',                             category: 'tool',      modifiers: ['Ctrl', 'Alt'] },
      // Edit
      KeyZ: { label: 'Undo',          description: '',                                           category: 'edit',      modifiers: ['Ctrl'] },
      // Selection
      KeyA: { label: 'Select All',    description: '',                                           category: 'selection', modifiers: ['Ctrl'] },
      KeyD: { label: 'Deselect',      description: '',                                           category: 'selection', modifiers: ['Ctrl'] },
      // View / Zoom
      Equal:  { label: 'Zoom In',     description: '',                                           category: 'view',      modifiers: ['Ctrl'] },
      Minus:  { label: 'Zoom Out',    description: '',                                           category: 'view',      modifiers: ['Ctrl'] },
      Digit0: { label: 'Fit Screen',  description: 'Zoom to fit',                                category: 'view',      modifiers: ['Ctrl'] },
      Digit1: { label: '100% Zoom',   description: 'Zoom to 100%',                               category: 'view',      modifiers: ['Ctrl'] },
      Digit2: { label: '200% Zoom',   description: 'Zoom to 200%',                               category: 'view',      modifiers: ['Ctrl'] },
      // Layers
      KeyN:         { label: 'New Layer',     description: 'Add new layer',     category: 'edit', modifiers: ['Ctrl', 'Alt', 'Shift'] },
      BracketRight: { label: 'Bring Fwd',     description: 'Bring forward',     category: 'edit', modifiers: ['Ctrl'] },
      BracketLeft:  { label: 'Send Back',     description: 'Send backward',     category: 'edit', modifiers: ['Ctrl'] },
      Comma:        { label: 'Hide Layers',   description: '',                  category: 'edit', modifiers: ['Ctrl'] },
      Slash:        { label: 'Lock Layers',   description: '',                  category: 'edit', modifiers: ['Ctrl'] },
      // Settings
      KeyK: { label: 'Settings',      description: 'Show settings',                              category: 'view',      modifiers: ['Ctrl'] },
    },
  },
  {
    id: 'premiere',
    name: 'Adobe Premiere Pro',
    icon: '<img src="icons/premier-pro-icon.svg" alt="Adobe Premiere Pro" class="template-logo">',
    appCategory: 'Video',
    hotkeys: {
      // Markers / in-out (bare keys)
      KeyI:      { label: 'Mark In',      description: 'Set in point',                        category: 'selection', modifiers: [] },
      KeyO:      { label: 'Mark Out',     description: 'Set out point',                       category: 'selection', modifiers: [] },
      KeyM:      { label: 'Add Marker',   description: 'Add marker at playhead',              category: 'edit',      modifiers: [] },
      KeyX:      { label: 'Mark Clip',    description: 'Mark in/out to clip edges',           category: 'selection', modifiers: [] },
      Slash:     { label: 'Mark Select',  description: 'Mark selection',                      category: 'selection', modifiers: [] },
      // Sequence editing (bare keys)
      KeyF:      { label: 'Match Frame',  description: 'Match frame to source',               category: 'view',      modifiers: [] },
      KeyE:      { label: 'Extend Edit',  description: 'Extend selected edit to playhead',    category: 'edit',      modifiers: [] },
      Comma:     { label: 'Insert',       description: 'Insert clip at playhead',             category: 'edit',      modifiers: [] },
      Period:    { label: 'Overwrite',    description: 'Overwrite clip at playhead',          category: 'edit',      modifiers: [] },
      Semicolon: { label: 'Lift',         description: 'Lift selection (leaves gap)',         category: 'edit',      modifiers: [] },
      Quote:     { label: 'Extract',      description: 'Extract selection (closes gap)',      category: 'edit',      modifiers: [] },
      Enter:     { label: 'Render',       description: 'Render effects in to out',            category: 'view',      modifiers: [] },
      Equal:     { label: 'Zoom In',      description: 'Zoom into timeline',                  category: 'view',      modifiers: [] },
      Minus:     { label: 'Zoom Out',     description: 'Zoom out of timeline',                category: 'view',      modifiers: [] },
      // Edit menu (Ctrl)
      KeyZ:      { label: 'Undo',         description: '',                                    category: 'edit',      modifiers: ['Ctrl'] },
      KeyA:      { label: 'Select All',   description: '',                                    category: 'selection', modifiers: ['Ctrl'] },
      KeyD:      { label: 'Video Trans',  description: 'Apply default video transition',      category: 'edit',      modifiers: ['Ctrl'] },
      KeyK:      { label: 'Add Edit',     description: 'Cut all tracks at playhead',          category: 'edit',      modifiers: ['Ctrl'] },
      KeyG:      { label: 'Group',        description: 'Group selected clips',                category: 'edit',      modifiers: ['Ctrl'] },
      KeyR:      { label: 'Speed/Dur',    description: 'Speed / Duration dialog',             category: 'edit',      modifiers: ['Ctrl'] },
      KeyL:      { label: 'Link',         description: 'Link / unlink selected clips',        category: 'edit',      modifiers: ['Ctrl'] },
      KeyU:      { label: 'Subclip',      description: 'Make subclip',                       category: 'edit',      modifiers: ['Ctrl'] },
      KeyT:      { label: 'New Text',     description: 'New text layer',                      category: 'edit',      modifiers: ['Ctrl'] },
      // File (Ctrl)
      KeyS:      { label: 'Save',         description: '',                                    category: 'file',      modifiers: ['Ctrl'] },
      KeyN:      { label: 'New Seq',      description: 'New sequence',                        category: 'file',      modifiers: ['Ctrl'] },
      // Window panels (Shift)
      Digit2:    { label: 'Source Mon',   description: 'Focus Source Monitor panel',         category: 'view',      modifiers: ['Shift'] },
      Digit3:    { label: 'Timeline',     description: 'Focus Timeline panel',               category: 'view',      modifiers: ['Shift'] },
      Digit4:    { label: 'Program Mon',  description: 'Focus Program Monitor panel',        category: 'view',      modifiers: ['Shift'] },
    },
  },
  {
    id: 'wow',
    name: 'World of Warcraft',
    icon: '<img src="icons/WoW_icon.svg" alt="World of Warcraft" class="template-logo">',
    appCategory: 'Gaming',
    hotkeys: {
      KeyW: { label: 'Move Fwd',      description: 'Move forward',              category: 'movement',  modifiers: [] },
      KeyA: { label: 'Turn Left',     description: 'Turn / strafe left',        category: 'movement',  modifiers: [] },
      KeyS: { label: 'Move Back',     description: 'Move backward',             category: 'movement',  modifiers: [] },
      KeyD: { label: 'Turn Right',    description: 'Turn / strafe right',       category: 'movement',  modifiers: [] },
      KeyQ: { label: 'Strafe L',      description: 'Strafe left',               category: 'movement',  modifiers: [] },
      KeyE: { label: 'Strafe R',      description: 'Strafe right',              category: 'movement',  modifiers: [] },
      Space: { label: 'Jump',         description: '',                           category: 'movement',  modifiers: [] },
      Digit1: { label: 'Ability 1',   category: 'combat',   modifiers: [] },
      Digit2: { label: 'Ability 2',   category: 'combat',   modifiers: [] },
      Digit3: { label: 'Ability 3',   category: 'combat',   modifiers: [] },
      Digit4: { label: 'Ability 4',   category: 'combat',   modifiers: [] },
      Digit5: { label: 'Ability 5',   category: 'combat',   modifiers: [] },
      Digit6: { label: 'Ability 6',   category: 'combat',   modifiers: [] },
      Digit7: { label: 'Ability 7',   category: 'combat',   modifiers: [] },
      Digit8: { label: 'Ability 8',   category: 'combat',   modifiers: [] },
      Digit9: { label: 'Ability 9',   category: 'combat',   modifiers: [] },
      Digit0: { label: 'Ability 10',  category: 'combat',   modifiers: [] },
      Tab: { label: 'Target Enemy',   description: 'Target nearest enemy',      category: 'combat',    modifiers: [] },
      KeyF: { label: 'Interact',      description: 'Interact / target',         category: 'combat',    modifiers: [] },
      KeyB: { label: 'Bags',          description: 'Open all bags',             category: 'tool',      modifiers: [] },
      KeyC: { label: 'Character',     description: 'Character sheet',           category: 'tool',      modifiers: [] },
      KeyI: { label: 'Inventory',     description: 'Open backpack',             category: 'tool',      modifiers: [] },
      KeyM: { label: 'Map',           description: 'Toggle zone map',           category: 'tool',      modifiers: [] },
      KeyN: { label: 'Talents',       description: 'Talent / spec panel',       category: 'tool',      modifiers: [] },
      KeyP: { label: 'Spellbook',     description: 'Open spellbook',            category: 'tool',      modifiers: [] },
      KeyG: { label: 'Guild',         description: 'Open guild roster',         category: 'tool',      modifiers: [] },
      KeyV: { label: 'Nameplates',    description: 'Toggle friendly nameplates',category: 'view',      modifiers: [] },
      ArrowUp:    { label: 'Cam Up',    category: 'view', modifiers: [] },
      ArrowDown:  { label: 'Cam Down',  category: 'view', modifiers: [] },
      ArrowLeft:  { label: 'Cam Left',  category: 'view', modifiers: [] },
      ArrowRight: { label: 'Cam Right', category: 'view', modifiers: [] },
    },
  },
  {
    id: 'vscode',
    name: 'VS Code',
    icon: '<img src="icons/vscode_icon.svg" alt="VS Code" class="template-logo">',
    appCategory: 'Development',
    hotkeys: {
      KeyS: { label: 'Save',          description: 'Save file',                 category: 'file',      modifiers: ['Ctrl'] },
      KeyW: { label: 'Close Tab',     description: 'Close editor tab',          category: 'file',      modifiers: ['Ctrl'] },
      KeyN: { label: 'New File',      description: 'New untitled file',         category: 'file',      modifiers: ['Ctrl'] },
      KeyP: { label: 'Quick Open',    description: 'Open file by name',         category: 'file',      modifiers: ['Ctrl'] },
      KeyZ: { label: 'Undo',          description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
      KeyY: { label: 'Redo',          description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
      KeyX: { label: 'Cut',           description: 'Cut line or selection',     category: 'edit',      modifiers: ['Ctrl'] },
      KeyC: { label: 'Copy',          description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
      KeyV: { label: 'Paste',         description: '',                           category: 'edit',      modifiers: ['Ctrl'] },
      KeyD: { label: 'Select Next',   description: 'Select next occurrence',    category: 'selection', modifiers: ['Ctrl'] },
      Slash: { label: 'Comment',      description: 'Toggle line comment',       category: 'edit',      modifiers: ['Ctrl'] },
      KeyF: { label: 'Find',          description: 'Find in file',              category: 'edit',      modifiers: ['Ctrl'] },
      KeyH: { label: 'Replace',       description: 'Find and replace',          category: 'edit',      modifiers: ['Ctrl'] },
      KeyG: { label: 'Go to Line',    description: 'Jump to line number',       category: 'movement',  modifiers: ['Ctrl'] },
      KeyB: { label: 'Sidebar',       description: 'Toggle activity bar',       category: 'view',      modifiers: ['Ctrl'] },
      Backquote: { label: 'Terminal', description: 'Toggle integrated terminal',category: 'view',      modifiers: ['Ctrl'] },
      F2:  { label: 'Rename',         description: 'Rename symbol',             category: 'edit',      modifiers: [] },
      F12: { label: 'Go to Def',      description: 'Go to definition',          category: 'movement',  modifiers: [] },
      F5:  { label: 'Debug',          description: 'Start / continue debug',    category: 'tool',      modifiers: [] },
      Home: { label: 'Line Start',    description: 'Go to line beginning',      category: 'movement',  modifiers: [] },
      End:  { label: 'Line End',      description: 'Go to line end',            category: 'movement',  modifiers: [] },
    },
  },
];
